<?php
/**
 * GEMBOK Configuration File
 * Generated by installer on: 2026-03-28 22:08:12
 */

// Database Configuration
define('DB_HOST', 'localhost');
define('DB_NAME', 'nolanet_db');
define('DB_USER', 'nolanet');
define('DB_PASS', 'nolaku');

// MikroTik Configuration
define('MIKROTIK_HOST', '172.17.1.1');
define('MIKROTIK_USER', 'noalnet');
define('MIKROTIK_PASS', 'noalku');
define('MIKROTIK_PORT', 8729);

// Application Configuration
define('APP_NAME', 'GEMBOK');
if (php_sapi_name() !== 'cli' && isset($_SERVER['HTTP_HOST'])) {
    $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
    $scriptDir = str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME']));
    $scriptDir = preg_replace('#/(admin|api|portal|cron|webhooks|install_steps|includes|sales|templates|technician)$#', '', $scriptDir);
    $scriptDir = rtrim($scriptDir, '/');
    define('APP_URL', $protocol . '://' . $_SERVER['HTTP_HOST'] . $scriptDir);
} else {
    define('APP_URL', 'http://localhost');
}
define('APP_VERSION', '3.0.1');
define('GEMBOK_UPDATE_VERSION_URL', 'https://raw.githubusercontent.com/zxxahsan/gembok/main/version.txt');

// Pagination
define('ITEMS_PER_PAGE', 20);
define('INVOICE_PREFIX', 'INV');
define('INVOICE_START', 1);

// Security
define('ENCRYPTION_KEY', 'bc3f2957c95e0740708361bd13ed93a41199fc9f92625660bb14de5d333b1055');

// WhatsApp Configuration
define('WHATSAPP_API_URL', '');
define('WHATSAPP_TOKEN', '');

// Tripay Configuration
define('TRIPAY_API_KEY', '');
define('TRIPAY_PRIVATE_KEY', '');
define('TRIPAY_MERCHANT_CODE', '');

// Telegram Configuration
define('TELEGRAM_BOT_TOKEN', '');

// GenieACS Configuration
define('GENIEACS_URL', 'http://localhost:7557');
define('GENIEACS_USERNAME', '');
define('GENIEACS_PASSWORD', '');